### ISSUE TITLE
LM4 Commands System

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#422]
# Description

LM4's commands are being re-written using [CommandAPI](https://www.spigotmc.org/resources/62353/), instead of our old Bukkit TabExecutor wrapper. This vastly simplifies the code for the command and brings a wealth of Brigadier's features such as entity selectors (e.g. `@e[type=zombie,distance=3]`), automatic tab completion, and so much more.

# To-do List

> :warning: To keep this to-do list easy to read, when a branch is complete, it is **removed** from the list.
> It will always appear like nothing is getting done here, but realistically, the completed tasks are just vanishing away. :)

- Command Implementations
  - `backup`
    - [ ] Implement
      - [ ] Test
    - [ ] Add translatable messages 
      - [ ] Test
  - `egg`
    - [ ] Implement
      - [ ] Test
    - [ ] Add translatable messages 
      - [ ] Test
  - `kill`
    - [ ] Add translatable messages
      - [ ] Test
  - `spawner`
    - [ ] Implement
      - [ ] Test
    - [ ] Add translatable messages
      - [ ] Test
  - `summon`
    - [ ] Implement custom entities summon subcommand
      - [ ] Test
    - [ ] Add translatable messages
      - [ ] Test
  - `routine`
    - [ ] Implement `halt` routine
      - [ ] Test
    - [ ] Implement `reset-configs` routine
      - [ ] Test
    - [ ] Improve formatting of all of the routine messages
      - [ ] Test

**Comment by stumper66** [comment]
This is no longer applicable
