### ISSUE TITLE
LM4 Buffs System

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#424]
> Note: To keep this issue easy to read, completed branches of this to-do list are removed once they are completed.

- [x] Creeper Blast Radius BuffType
  - [x] Implement
- [x] Implement Exp Drop BuffType
  - [x] Implement
- [x] Implement Item Drop BuffType
  - [x] Implement most of it
  - [x] Quick test
  - [x] Wait for the custom drops system to be implemented (#423)
  - [x] Implement the custom drops system to check if custom drops can be multiplied by this.
- [ ] Implement Shield Breaker BuffType
  - *See #379 and #329 for more information.*
  - [x] Implement entity key store and data methods
  - [ ] Implement required listeners
    - [ ] On hold: Bukkit API does not contain the required code, see https://github.com/PaperMC/Paper/issues/8751

**Comment by lokka30** [comment]
Pseudocode for Item Drop Multiplication

```
fun handleItemDrops(event) -> void:
    let vanillaDrops = empty list <ItemStack>
    let customDrops = empty list <ItemStack>
    let nonVanillaDrops = empty list <ItemStack>

    sortItemDrops(event, vanillaDrops, customDrops, nonVanillaDrops)

    
    handleCustomItemDrops(event, vanillaDrops, customDrops, nonVanillaDrops)
    handleMultipliedItemDrops(event, vanillaDrops, customDrops, nonVanillaDrops)

    event.getItems().clear()
    event.getItems().addAll(vanillaDrops)
    event.getItems().addAll(customDrops)
    event.getItems().addAll(nonVanillaDrops)

fun sortItemDrops(event, vanillaDrops, customDrops, nonVanillaDrops) -> void:
    let originalDrops = event.getItems()

    for originalDrop in originalDrops:
        if originalDrop is not in entity's drop table or is in inventory:
            nonVanillaDrops.add(originalDrop)
        else:
            vanillaDrops.add(originalDrop)

fun handleCustomItemDrops(event, vanillaDrops, customDrops, nonVanillaDrops) -> void:
    let result = CustomDropHandler.createDropResult(event)

    customDrops.addAll(result.getItems())

    // check if we should override vanilla drops
    if result.overridesVanillaDrops(default=false):
        vanillaDrops.clear()

    if result.overridesNonVanillaDrops(default=false):
        nonVanillaDrops.clear()

    

fun handleMultipliedItemDrops(event, vanillaDrops, customDrops, nonVanillaDrops) -> void:
    let entityDropMult = evaluated entity drop multiplier formula

    let dropMultiplier: BiConsumer<ItemStack drop, Double mult> = (drop, mult) ->
        drop.setAmount(Math.min(drop.getAmount() * mult, drop.getMaxStackSize())); 

    for vanillaDrop in vanillaDrop:
        dropMultiplier.apply(vanillaDrop);

    for customDrop in customDrops:
        if customDrop is not multipliable:
            continue
        
        dropMultiplier.apply(customDrop);
    
    if AdvancedSettings.MultiplyNonVanillaDrops(default=false):
        for nonVanillaDrop in nonVanillaDrops:
            dropMultiplier.apply(nonVanillaDrop);
```

**Comment by lokka30** [comment]
# LM4 Custom Drops Config Changes

> **(Incomplete: check to-do's.)**

## Brainstorm Preview

### File Structure

```yaml
# Per-Entity-Type Drops
CREEPER:
    overall-chance: 100 # = 100% overall chance for any items to be processed
    items:
      - material: "NETHERITE_SWORD"
        name: "&cLegendary Broadsword"
        chance: 0.5 # 0.5%
        amount: 1-5
        min-level: 95
        max-level: 100

# Drop Tables
drop-tables:
  - id: 'BrainEaters'
    entities:
        in-list: ['ZOMBIE', 'HUSK', 'DROWNED']
    items:
      - material: "NETHERITE_SWORD"
        name: "&cLegendary Broadsword"
        chance: 0.5 # 0.5%
        amount: 1-5
        min-level: 95
        max-level: 100
```

## To-do

- [ ] Decide how these will (or won't) be changed in LM 4:

```yaml
min-player-level: -1
max-player-level: -1
maxdropgroup: 1
item_flags: ''
groupid: ''
nbt-data: ''
only-drop-if-equipped: false
player-level-variable: ''
overall_permission: ['']
permission: ['']
cause-of-death: ['']
run-on-spawn: false
run-on-death: true
delay: 0
```

## Unchanged; same as LM3

```yaml
amount: 32
name: '&dBlazed Pearl Broadsword'
lore: ['&f&oForged from Wither ashes.']
player-caused: true
```

## Notable removals in LM3 -> LM4 CustomDrops

> Priority was removed since custom drops will be processed in order.

```yaml
priority: 5
```

## Generic Formatting Changes

> No behavioural changes - just keeping the key name formatting consistent.

LM3:

```yaml
minLevel: 12
maxLevel: 34
custommodeldata: 123
nomultiplier: true
nospawner: false
```

LM4:

```yaml
min-level: 12
max-level: 34
custom-model-data: 123
no-multiplier: true
no-spawner: false
```

## Root Item Section

> LM4 removes the material node acting as a parent for the rest of the drop's nodes, as that is redundant and promotes indentation errors.

LM3:

```yaml
- DIAMOND_SWORD:
    name: 'Sword of a Thousand Truths'
```

LM4:

```yaml
- material: "DIAMOND_SWORD"
  name: 'Sword of a Thousand Truths'
```

## Chances

> **About:** Chance that an item will drop.

> Demonstrating a `15%` chance.

LM3:

```yaml
chance: 0.15 
```

LM4:

```yaml
chance: 15
```

## Chunk Kill Count

> **About:** The item will be limited by LM's chunk kill count system.

LM3:

```yaml
use-chunk-kill-max: true
```

LM4:

```yaml
chunk-kill-limited: true 
```

## Durability Loss (Damage)

> **About:** Represents a decrease in durability

LM3:

```yaml
damage: 10
```

LM4:

```yaml
durability-loss: 10
```

## Equipment

LM3:

```yaml
equipped: 1.0
equip-offhand: true
```

LM4:

```yaml
# if equipment-slots is specified then the item WILL be equipped, just a matter of 'where?'.
# LM will attempt to put the item in any of the slots, in order.
# Equipped items will be limited to their material's stack size and will not use any overflow logic.
equipment-slots: ['MAIN_HAND', 'OFF_HAND', 'HELMET', 'CHESTPLATE', 'LEGGINGS', 'BOOTS']
```

## Enchantments

LM3:

```yaml
enchantments:
    ENCHANTMENT: X
enchantments:
    ENCHANTMENT:
        shuffle: false
        default: 1
        X: 0.5
```

LM4:

> Removed Shuffle and Default - deemed unnecessary.

```yaml
enchantments:
  - SHARPNESS: 5
  - KNOCKBACK: 1
      chance: 0.5
  - KNOCKBACK: 2
      chance: 0.25
```

## Overrides Vanilla Drops

LM3:

```yaml
override: true
```

LM4:

```yaml
overrides-vanilla-drops: true
```

## Overall Chances

LM3:

```yaml
CREEPER:
  - DIAMOND_SWORD:
        overall_chance: 0.750112
ZOMBIE:
  - DIAMOND_SWORD:
        overall_chance: 0.2357
```

LM4:

```yaml
CREEPER:
    overall-chance: 75.0112 # = 75.0112% overall chance for any items to be processed
    items:
      - material: "NETHERITE_SWORD"

ZOMBIE:
    overall-chance: 23.57   # = 23.57% overall chance for any items to be processed
    items:
      - material: "APPLE"
```

**Comment by lokka30** [comment]
- [ ] Oath I noticed your pastebin said that non-shuffled items have priority, I switched it up and made shuffle irrelevant to priority. Do you prefer this style?

- [ ] also, we'll probably need to speak about how this works before we implement this:
`-    Collect CustomRules specific drop-tables from CD `

- [ ] and additionally, need to check whether enchantment shuffling is better or worse than my proposed new enchantments system:

  > Before understanding the enchantment shuffle system I changed the way enchantments were declared in the CD file, what do you think of the idea in the link above? Does this supersede enchantment shuffling, or vice-versa?

**Comment by lokka30** [comment]
Shield breaker feature is on-hold due to the lack of required API. https://github.com/PaperMC/Paper/issues/8751
