### ISSUE TITLE
[LM4b] To-do List

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#457]
A new to-do list for yet another revision of LM4. 😄 

- **It's listed in order of what should be done first, though the list is pretty flexible, so no need to follow it strictly.**
- **This list is not definitive, it is being edited very frequently, tasks are constantly being added.**
- **A checkmark indicates that a task is work-in-progress. Completed tasks are removed from the list entirely.**
- **Assigness are merely a suggestion, anyone in the team can work on anything.**
- **LM4 accepts contributions, let me know if there's something you'd like to work on.** 🙂

### List

- [x] Reimplement API from LM4a (@lokka30)
  - so we can get started using PDC stuff. :)
- [ ] Complete the [EntityLabelLib](https://github.com/ArcanePlugins/EntityLabelLib) project.
- [ ] Implement various actions
  - Fundamental
    - [x] `exit-rule` (@lokka30)
      - Terminates the current rule.
    - [x] `exit-rules` (@lokka30)
      - If a rule running `exit-rules` has been called by another rule, then LM will recursively exit each rule's caller.
      - Exact same as `exit-all` from LM4a, just renamed.
    - [x] `call-rule` (@lokka30)
      - Runs another rule, then continues on with the rest of the calling rule's actions.
      - Exactly like calling a function within another function when programming.
    - [ ] `set-buffs` (@lokka30)
    - [ ] `set-level` (@lokka30)
    - [ ] `deny-level` (@lokka30)
      - Makes it so a mob cannot be levelled (unless explicitly overridden).
  - Basic
    - [ ] `broadcast-to-server` (@stumper66)
    - [ ] `broadcast-to-nearby-players` (@stumper66)
    - [ ] `broadcast-to-world` (@stumper66)
  - [ ] Have it all tested by volunteers
- [ ] Implement more conditions
  - [ ] `chance` (@stumper66)
  - [ ] `entity-level` (@lokka30)
  - [ ] `entity-biome` (@stumper66)
  - [ ] `entity-custom-name-contains` (@stumper66)
  - [ ] `entity-owner` (@lokka30)
  - [ ] `entity-type` (@stumper66)
  - [ ] `entity-world` (@stumper66)
  - [ ] `player-world` (@stumper66)
  - [ ] `player-gamemode` (@stumper66)
  - [ ] Have it all tested by volunteers
- [ ] Implement more triggers using additional listeners
  - [ ] `entity-breed` (@lokka30)
  - [ ] `entity-damage` (@lokka30)
  - [ ] `entity-damage-by-entity` (@lokka30)
  - [ ] `entity-death` (@lokka30)
  - [ ] `entity-explode` (@lokka30)
  - [ ] `entity-regain-health` (@lokka30)
  - [ ] `entity-transform` (@lokka30)
  - [ ] `player-death` (@lokka30)
  - [ ] `player-join` (@lokka30)
  - [ ] `player-quit` (@lokka30)
  - [ ] `player-teleport` (@lokka30)
  - [ ] `player-changed-world` (@lokka30)
  - [ ] Have it all tested by volunteers
- [ ] Implement presets (`presets.yml`) (@lokka30)
  - [ ] Have it tested by volunteers
- [ ] Implement groups (`groups.yml`) (@lokka30)
  - [ ] Implement group related actions (@lokka30)
  - [ ] Have it tested by volunteers
- [ ] Plan out and develop Simple Settings. (@lokka30, @UltimaOath, @stumper66)
  - [ ] Have testers check Simple Settings works especially when combined with `rules.yml`.
- [ ] Brainstorm how nametags will work. (@lokka30, @UltimaOath, @stumper66)
  - [ ] Implement actions (@lokka30)
    - [ ] `set-death-label` (@lokka30)
    - [ ] `set-permanent-label` (@lokka30)
    - [ ] `set-packet-label` (@lokka30)
    - [ ] `update-labels` (@lokka30)
    - [ ] Have testers check the new actions.
- [ ] Work on custom drops. (@lokka30)
  - Custom drops was done well in LM4a so check out that redesign and implementation.
  - [ ] Implement CDs (@lokka30)
  - [ ] Have testers check the initial CDs system.
  - [ ] Work on actions for custom drops. (@lokka30)
    - [ ] `add-drop-tables` (@lokka30)
    - [ ] `set-drop-tables` (@lokka30)
    - [ ] `remove-drop-tables` (@lokka30)
  - [ ] Implement chunk kill count cap (@stumper66, @lokka30)
  - [ ] Have testers check the whole CD system including chunk kill count and the CD actions.
- [ ] Work on integrations. (@lokka30)
  - [ ] NBT API (@lokka30)
    - [ ] Create action `add-nbt-tag` (@lokka30)
  - [ ] Other integrations to work on?.. (unassigned)
  - [ ] Have testers check integrations work. 
- [x] Work on Javadocs, basically all comments saying `//TODO doc`. (@lokka30)
- [ ] Work on documentation.
  - We can't write the whole thing, otherwise release will be delayed a lot, though we should get it to a level where we list all options and tell beginners how they can use LM4.
- [ ] Prepare changelog.
- [ ] Prepare update announcements.
- [ ] Release!

**Comment by lokka30** [comment]
@stumper66 Should this issue be closed or repurposed?

**Comment by stumper66** [comment]
Let's close it since most doesn't apply anymore.
